[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'cd frontend && npm install --legacy-peer-deps && npm run build && cd ..'
]

[start]
cmd = 'cd backend && python app.py'
